#!/usr/bin/env bash

python-lambda-template
terraform/config/prod.config



python_lambda_template
  .github/workflows/deploy.yaml
    PAK_NAME: python_lambda_template
  .github/workflows/deploy.yaml
    PAK_NAME: python_lambda_template
  python_lambda_template/
  tests/test_python_lambda_template.oy
    from python_lambda_template import __version__